# Generated by Django 5.1.6 on 2025-02-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('T_name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Pass_word', models.CharField(max_length=100)),
                ('Moblie_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('Date_of_Joining', models.DateField()),
            ],
        ),
    ]
